nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - '/Users/zhongjunbin/Document/Kitematic/nginx:/opt'
php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
    volumes:
      - '/Users/zhongjunbin/Document/Kitematic/nginx/htdocs:/opt/htdocs'
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - '/Users/zhongjunbin/Document/Kitematic/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
memcache:
    build: ./memcache
    ports:
      - "11211:11211"
elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - '/Users/zhongjunbin/Document/Kitematic/elasticsearch/data:/usr/share/elasticsearch/data'
