nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - '$HOME/Document/Kitematic/nginx:/opt'
php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
    volumes:
      - '$HOME/Document/Kitematic/nginx/htdocs:/opt/htdocs'
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - '$HOME/Document/Kitematic/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
memcache:
    build: ./memcache
    ports:
      - "11211:11211"
elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - '$HOME/Document/Kitematic/elasticsearch/data:/usr/share/elasticsearch/data'
postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - '$HOME/Document/Kitematic/postgres:/var/lib/postgresql'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - '$HOME/Document/Kitematic/mongodb:/data'
redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - '$HOME/Document/Kitematic/redis:/data'
rabbit1:
  build: ./rabbitMQ
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "15672:15672"
rabbit2:
  build: ./rabbitMQ
  hostname: rabbit2
  links:
    - rabbit1
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
   - RAM_NODE=true
  ports:
      - "5673:5672"
      - "15673:15672"
rabbit3:
  build: ./rabbitMQ
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
  ports:
        - "5674:5672"
