nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - '/Users/zhongjunbin/Document/Kitematic/nginx:/opt'
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - '/Users/zhongjunbin/Document/Kitematic/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
